admin_users:
    path: /admin/users
    controller: App\Controller\Admin\UsersController::getAllUsers

admin_jobs:
    path: /admin/jobs
    controller: App\Controller\Admin\JobsController::getAllJobs

admin_categories:
    path: /admin/categories
    controller: App\Controller\Admin\CategoriesController::adminGetCategories

admin_category_delete:
    path: /admin/category/delete/{id}
    controller: App\Controller\Admin\CategoriesController::adminDeleteCategory