admin_category:
    path: /admin/category
    controller: App\Controller\Admin\CategoriesController::adminGetCategories

admin_category_delete:
    path: /admin/category/delete/{id}
    controller: App\Controller\Admin\CategoriesController::adminDeleteCategory